code --install-extension ahmadawais.shades-of-purple
code --install-extension andys8.jest-snippets
code --install-extension azemoh.one-monokai
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension chenxsan.vscode-standardjs
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension ionutvmi.path-autocomplete
code --install-extension luongnd.edge
code --install-extension mikestead.dotenv
code --install-extension mohsen1.prettify-json
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension octref.vetur
code --install-extension Orta.vscode-jest
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension ritwickdey.LiveServer
code --install-extension ronnidc.nunjucks
code --install-extension stylelint.vscode-stylelint
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
